core_case_data:
  api:
    url: ${CCD_DATA_STORE_API_BASE_URL:http://localhost:4452}
idam:
  username: ${IDAM_USERNAME}
  password: ${IDAM_PASSWORD}

  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: civil
    redirect_uri: https://localhost:9000/oauth2/callback
    secret: OOOOOOOOOOOOOOOO
  s2s-auth:
    microservice: civil_service
    totp_secret: AABBCCDDEEFFGGHH
    url: ${IDAM_S2S_URL:http://localhost:4502}
migration:
  caseIds: ${MIGRATION_CASE_IDS:}
  caseType: ${MIGRATION_CASE_TYPE}
  dryRun: ${MIGRATION_DRY_RUN:false}
  maxCasesToProcess: ${MIGRATION_CASE_LIMIT:80000}
  numThreads: ${MIGRATION_NO_OF_THREADS:20}
  esEnabled: ${MIGRATION_ES_ENABLED:false}
  esQuerySize: ${MIGRATION_ES_QUERY_SIZE:500}

spring:
  application:
    name: ccd-case-migration-tool
logging:
  level:
    root: ERROR
    uk:
      gov:
        hmcts:
          reform: INFO
          reform.migration: ${log.level:INFO}
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
