job:
  image: 'hmctspublic.azurecr.io/civil/civil-ccd-case-migration:latest'
  kind: CronJob
  schedule: "0 22 * * *"
  ingressHost: civil-ccd-migration-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: civil
#  Uncomment once the vault containing the app insights key has been set up
  keyVaults:
    ccd:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    CCD_DATA_STORE_API_BASE_URL:
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_API_URL:
    IDAM_CLIENT_ID: ccd_gateway
    IDAM_CLIENT_REDIRECT_URI:
    IDAM_USERNAME: test-user
    IDAM_PASSWORD: test_pass
    MIGRATION_ID:
    MIGRATION_CASE_TYPE: case_type_1
    MIGRATION_CASE_EVENT_ID: migrateCase
    MIGRATION_CASE_EVENT_DESC: Migrate Case
    MIGRATION_CASE_EVENT_SUMMARY: Migrate Case
    MIGRATION_ES_ENABLED: true

